name: Build Docker iStoreOS

on:
  push:
  schedule:
    - cron: '0 10 * * 1'  # 每周一的上午10点（UTC时间，对应北京时间下午6点）
  workflow_dispatch:
    inputs:
      ipaddr:
        description: '输入管理IP'
        required: true
        default: '192.168.1.100'
      gateway:
        description: '输入默认网关'
        required: true
        default: '192.168.1.1'
      version:
        description: '输入版本号,格式为X.Y.Z,为空则版本号加1'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 下载构建文件
        run: |
          wget https://fw0.koolcenter.com/iStoreOS/alpha/24.10/ib/armsr/istoreos-imagebuilder-armsr-armv8.Linux-x86_64.tar.zst
          echo "解压文件"
          zstd -d -c istoreos-imagebuilder-armsr-armv8.Linux-x86_64.tar.zst | tar -xvf -
          # wget https://fw0.koolcenter.com/iStoreOS/alpha/24.10/ib/x86_64/istoreos-imagebuilder-x86-64.Linux-x86_64.tar.zst

      - name: 设置文件
        run: |
          cd istoreos-imagebuilder-armsr-armv8.Linux-x86_64
          echo "生成rootfs.tar.gz配置"
          sed -i 's/# CONFIG_TARGET_ROOTFS_TARGZ is not set/CONFIG_TARGET_ROOTFS_TARGZ=y/' .config





          
